# Generated by Django 5.2.1 on 2025-06-23 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('linhas_lidas', models.IntegerField(default=0)),
                ('projetos_criados', models.IntegerField(default=0)),
                ('projetos_ignorados', models.IntegerField(default=0)),
                ('linhas_ignoradas_texto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criado_por', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Criado por (e-mail)')),
                ('atualizado_por', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Atualizado por (e-mail)')),
                ('eh_remoto', models.BooleanField(default=False, verbose_name='É remoto')),
                ('formato', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto')], default='presencial', max_length=20, verbose_name='Formato')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('inscricoes_abertas', 'Inscrições Abertas'), ('avaliacao_inscricoes', 'Avaliação das Inscrições'), ('inscricoes_aprovadas', 'Inscrições Aprovadas'), ('em_andamento', 'Em Andamento'), ('avaliacao_projeto', 'Avaliação do Projeto'), ('finalizado', 'Finalizado')], default='rascunho', max_length=30, verbose_name='Status')),
                ('vagas', models.PositiveIntegerField(verbose_name='Vagas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('inicio_inscricoes', models.DateTimeField(verbose_name='Início das inscrições')),
                ('fim_inscricoes', models.DateTimeField(verbose_name='Fim das inscrições')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cidades_aceitas', models.ManyToManyField(blank=True, related_name='projetos', to='core.cidade', verbose_name='Cidades aceitas')),
                ('estados_aceitos', models.ManyToManyField(blank=True, related_name='projetos', to='core.estado', verbose_name='Estados aceitos')),
                ('regioes_aceitas', models.ManyToManyField(blank=True, related_name='projetos', to='core.regiao', verbose_name='Regiões aceitas')),
                ('tutora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_tutorados', to=settings.AUTH_USER_MODEL, verbose_name='Tutora')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
