# Generated by Django 5.2.1 on 2025-06-24 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('status_novo', models.CharField(max_length=30)),
                ('modificado_por', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modificado por (nome e e-mail)')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_status', to='projects.project')),
            ],
        ),
    ]
