# Generated by Django 5.2.1 on 2025-06-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatuslog',
            name='status_anterior_display',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projectstatuslog',
            name='status_novo_display',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
