# Generated by Django 5.2.1 on 2025-06-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('projects', '0003_projectstatuslog_status_anterior_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=10, null=True)),
                ('status_novo', models.CharField(max_length=10)),
                ('status_anterior_display', models.CharField(blank=True, max_length=50, null=True)),
                ('status_novo_display', models.CharField(max_length=50)),
                ('modificado_por', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modificado por (nome e e-mail)')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_status', to='applications.application')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
