# Generated by Django 5.2.1 on 2025-06-24 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aceite_declaracao_veracidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='aceite_requisitos_tecnicos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='anais_congresso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='apresentacao_oral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='application',
            name='autodeclaracao_racial',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='biologia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Biologia'),
        ),
        migrations.AddField(
            model_name='application',
            name='boletim_escolar',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='capitulo_publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='como_soube_programa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='concorrer_reserva_vagas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='cota_desejada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='cpf_anexo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='curriculo_lattes_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='curso_capacitacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='curso_extensao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='declaracao_vinculo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='docencia_medio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='docencia_superior',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='documentacao_comprobatoria_lattes',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='feira_ciencias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='fisica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Física'),
        ),
        migrations.AddField(
            model_name='application',
            name='geografia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Geografia'),
        ),
        migrations.AddField(
            model_name='application',
            name='historia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em História'),
        ),
        migrations.AddField(
            model_name='application',
            name='laudo_medico_deficiencia',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='livro_publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='matematica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Matemática'),
        ),
        migrations.AddField(
            model_name='application',
            name='missao_cientifica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='mulher_trans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='necessita_material_especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='orientacao_ic',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='orientacoes_estudantes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='participacoes_bancas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='perfil_academico',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='periodico_indexado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='portugues',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Português'),
        ),
        migrations.AddField(
            model_name='application',
            name='premiacoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='quimica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Química'),
        ),
        migrations.AddField(
            model_name='application',
            name='rg_frente',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rg_verso',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone inválido.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='application',
            name='termo_autorizacao',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tipo_deficiencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='tipo_material_necessario',
            field=models.TextField(blank=True),
        ),
    ]
